### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [Goose97/google_scraper#1]
Hello Duc 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. 

We hope you will follow this process in the code review process as you failed to follow this requirement:

![image](https://github.com/Goose97/google_scraper/assets/696529/51f00d09-05fd-46e7-85ef-cd7725d912cf)

Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇 

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by Goose97** [comment]
Great to hear from you. I'll get to it ASAP

**Comment by olivierobert** [comment]
Hi Duc. Thank you for your feedback on most of the open issues. We now have sufficient information to wrap up this stage of the code challenge. We will provide our feedback and information on the next step by email.

**Comment by Goose97** [comment]
Thanks Oliver. Had a great time working with you.
